### ISSUE TITLE
SagaAudit blows up with key not found ex when processing header less message

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl.Plugins.v5#4]
### Steps to repro:

1. Add a saga
2. Use queue explorer to create a new message, paste in the body of a message

### Exception

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ServiceControl.Plugin.SagaAudit.CaptureSagaStateBehavior.AuditSaga(Saga saga, IncomingContext context) in c:\BuildAgent\work\5d8e2b68f32aa08f\src\ServiceControl.Plugin.SagaAudit\CaptureSagaStateBehavior.cs:line 64

```

### Solution

Cater for the fact that the header collection can be empty on line 64-67:

https://github.com/Particular/ServiceControl.Plugins.v5/blob/master/src/ServiceControl.Plugin.SagaAudit/CaptureSagaStateBehavior.cs#L64

**Related Googlegroups post:**
https://groups.google.com/forum/#!topicsearchin/particularsoftware/saga$20audit$20plugin/particularsoftware/PoHI4Zj98kI

**Comment by indualagarsamy** [comment]
@andreasohlund - how can I repro this? If I try sending a new message via QueueExplorer I get a serialization exception, not the KeyNotFound exception.

**Comment by indualagarsamy** [comment]
Moved issue to new repository: 
https://github.com/Particular/ServiceControl.Plugin.Nsb5.SagaAudit/issues/2
